// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYKsYOXqYJa0lzy4f9rLm5Wht3_tEruw',
    appId: '1:232657733519:web:02ba82478a9c6fd6b62dfa',
    messagingSenderId: '232657733519',
    projectId: 'opel-heroes',
    authDomain: 'opel-heroes.firebaseapp.com',
    databaseURL: 'https://opel-heroes.firebaseio.com',
    storageBucket: 'opel-heroes.appspot.com',
    measurementId: 'G-FXTGTBVW2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTFL1fjioklXUI1DLjhu8W-YCD9bGjcc',
    appId: '1:232657733519:android:c93cf1c06c08a19fb62dfa',
    messagingSenderId: '232657733519',
    projectId: 'opel-heroes',
    databaseURL: 'https://opel-heroes.firebaseio.com',
    storageBucket: 'opel-heroes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6BRdUrpxS4OdcCzmCsabfKV1FmglQ2o',
    appId: '1:232657733519:ios:8413ff9efc4f693eb62dfa',
    messagingSenderId: '232657733519',
    projectId: 'opel-heroes',
    databaseURL: 'https://opel-heroes.firebaseio.com',
    storageBucket: 'opel-heroes.appspot.com',
    iosBundleId: 'com.rdb.pyramidsDevelopments',
  );
}
